"""The ngspice backend: deterministic decks, offline runs, honest results.

The result contract keeps four verdicts separate, because conflating
them is how a simulation quietly overstates itself:

  * ``backend`` - whether ngspice exists here at all, and which
    version ran. An absent backend yields status
    ``backend-unavailable``: not a pass, not a fabricated failure -
    policy decides what an optional backend's absence means.
  * ``converged`` - whether the simulator itself completed.
  * ``measurements`` - the numerical values and their assertion
    verdicts, meaningful only when the run converged.
  * ``model_coverage`` - which registered models, at which fidelity
    classes, produced those numbers. A PASS never implies stronger
    coverage than this block states, and ``significance`` says so in
    the result itself, with ``release_grade`` unconditionally false
    at this layer.

Decks are generated deterministically (sorted, fixed formatting) and
hashed; the raw simulator log is captured and hashed; missing models
refuse BEFORE any simulator runs.
"""

from __future__ import annotations

import hashlib
import os
import subprocess

from .fidelity import SimulationError
from . import scenario as scenario_module

NGSPICE_BINARY = "ngspice"


def backend_identity():
    """Discover ngspice: availability, path and version string."""
    import shutil
    path = shutil.which(NGSPICE_BINARY)
    if path is None:
        return {"name": "ngspice", "available": False, "path": None,
                "version": None,
                "detail": "ngspice binary not found on PATH"}
    try:
        probe = subprocess.run(
            [path, "--version"], capture_output=True, text=True,
            timeout=30)
        first = (probe.stdout or probe.stderr or "").strip()
        version = first.splitlines()[0] if first else "unknown"
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"name": "ngspice", "available": False, "path": path,
                "version": None,
                "detail": "ngspice exists but did not answer "
                          "--version: {}".format(exc)}
    return {"name": "ngspice", "available": True, "path": path,
            "version": version, "detail": "discovered on PATH"}


def _format_value(value):
    return repr(float(value))


def generate_deck(registry, sim_scenario):
    """A deterministic ngspice batch deck for one validated scenario.

    Element cards appear in the scenario's declared order (the order
    is part of the declaration); measurement outputs are written with
    wrdata to fixed filenames; models are inlined as subcircuits from
    the registry. Refuses on any unregistered model.
    """
    scenario_module.validate_scenario(sim_scenario)
    lines = ["* scenario: {}".format(sim_scenario["name"]),
             "* deterministic deck generated by pcbqa.sim.ngspice"]
    model_names = scenario_module.referenced_models(sim_scenario)
    for name in model_names:
        model = registry.get(name)
        spice = model.get("spice")
        if not spice:
            raise SimulationError(
                "model {!r} carries no spice text; it cannot be "
                "instantiated by this backend".format(name))
        lines.append("* model {} coverage={} source={}".format(
            name, ",".join("{}:{}".format(k, v) for k, v in
                           sorted(model["coverage"].items())),
            model["provenance"]["source"]))
        lines.extend(line.rstrip() for line in spice.splitlines())
    counters = {"resistor": 0, "capacitor": 0, "inductor": 0,
                "vsource": 0, "instance": 0}
    for element in sim_scenario["elements"]:
        kind = element["kind"]
        nodes = " ".join(element["nodes"])
        if kind == "resistor":
            counters["resistor"] += 1
            lines.append("R{} {} {}".format(
                element["name"], nodes,
                _format_value(element["value"])))
        elif kind == "capacitor":
            counters["capacitor"] += 1
            lines.append("C{} {} {}".format(
                element["name"], nodes,
                _format_value(element["value"])))
        elif kind == "inductor":
            counters["inductor"] += 1
            lines.append("L{} {} {}".format(
                element["name"], nodes,
                _format_value(element["value"])))
        elif kind == "vsource_dc":
            counters["vsource"] += 1
            lines.append("V{} {} DC {}".format(
                element["name"], nodes,
                _format_value(element["value"])))
        elif kind == "vsource_pulse":
            counters["vsource"] += 1
            pulse = element["pulse"]
            lines.append(
                "V{} {} PULSE({} {} {} {} {} {} {})".format(
                    element["name"], nodes,
                    _format_value(pulse["v1"]),
                    _format_value(pulse["v2"]),
                    _format_value(pulse["delay_s"]),
                    _format_value(pulse["rise_s"]),
                    _format_value(pulse["fall_s"]),
                    _format_value(pulse["width_s"]),
                    _format_value(pulse["period_s"])))
        else:  # model_instance
            counters["instance"] += 1
            lines.append("X{} {} {}".format(
                element["name"], nodes, element["model"]))
    conditions = sim_scenario.get("operating_conditions")
    if conditions is not None:
        # The declared condition genuinely reaches the simulator: this
        # is what licenses the scenario contract to accept it at all.
        lines.append(".options temp={}".format(
            _format_value(conditions["temperature_c"])))
    lines.append(".control")
    lines.append("set filetype=ascii")
    for analysis in sim_scenario["analyses"]:
        if analysis["kind"] == "op":
            lines.append("op")
            for m in sim_scenario["measurements"]:
                if m["kind"] == "op_voltage":
                    lines.append("wrdata op_{}.data v({})".format(
                        m["name"], m["node"]))
        else:
            lines.append("tran {} {}".format(
                _format_value(analysis["step_s"]),
                _format_value(analysis["stop_s"])))
            for m in sim_scenario["measurements"]:
                if m["kind"] == "tran_final_voltage":
                    lines.append("wrdata tran_{}.data v({})".format(
                        m["name"], m["node"]))
    lines.append("quit")
    lines.append(".endc")
    lines.append(".end")
    return "\n".join(lines) + "\n"


def _sha256_text(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _read_last_column_value(path):
    last = None
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            parts = line.split()
            if len(parts) >= 2:
                last = parts
    if last is None:
        raise SimulationError(
            "wrdata output {} carried no data rows".format(
                os.path.basename(path)))
    return float(last[-1])


def run_scenario(registry, sim_scenario, workdir):
    """Run one scenario. Every outcome is explicit; nothing is faked."""
    scenario_module.validate_scenario(sim_scenario)
    model_names = scenario_module.referenced_models(sim_scenario)
    requirement = sim_scenario.get("required_coverage")
    coverage = registry.coverage_report(model_names, requirement)
    if requirement is not None and not coverage["satisfied"]:
        unmet = sorted(
            phenomenon for phenomenon, record in
            coverage["per_phenomenon"].items() if not record["met"])
        raise SimulationError(
            "scenario coverage requirement is not satisfied for "
            "phenomen{} {}; a model never satisfies a phenomenon it "
            "does not cover, and the run refuses before any simulator "
            "starts".format("on" if len(unmet) == 1 else "a", unmet))
    deck = generate_deck(registry, sim_scenario)
    backend = backend_identity()
    result = {
        "scenario": sim_scenario["name"],
        "backend": backend,
        "deck_sha256": _sha256_text(deck),
        "model_coverage": coverage,
        "operating_conditions_applied":
            sim_scenario.get("operating_conditions"),
        "significance": {
            "release_grade": False,
            "meaning": "a numerical result under exactly the stated "
                       "model coverage; convergence and assertion "
                       "verdicts never imply stronger evidence than "
                       "model_coverage records",
        },
    }
    if not backend["available"]:
        result.update({"status": "backend-unavailable",
                       "converged": None, "measurements": None,
                       "unsupported": []})
        return result
    os.makedirs(workdir, exist_ok=True)
    deck_path = os.path.join(workdir, "deck.cir")
    with open(deck_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(deck)
    run = subprocess.run(
        [backend["path"], "-b", deck_path], capture_output=True,
        text=True, timeout=600, cwd=workdir)
    log = (run.stdout or "") + "\n" + (run.stderr or "")
    result["raw_log_sha256"] = _sha256_text(log)
    converged = run.returncode == 0 and "error" not in log.lower()
    result["converged"] = converged
    if not converged:
        result.update({"status": "simulation-failed",
                       "measurements": None,
                       "unsupported": [],
                       "failure_log_tail": log[-2000:]})
        return result
    measurements = {}
    for m in sim_scenario["measurements"]:
        prefix = "op" if m["kind"] == "op_voltage" else "tran"
        data_path = os.path.join(
            workdir, "{}_{}.data".format(prefix, m["name"]))
        value = _read_last_column_value(data_path)
        assertion = m.get("assertion")
        measurements[m["name"]] = {
            "value": value,
            "assertion": assertion,
            "passed": scenario_module.check_assertion(assertion, value),
        }
    result.update({"status": "ran", "measurements": measurements,
                   "unsupported": []})
    return result
